# Generated by Django 2.2 on 2019-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperHeroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('city_of_origin', models.CharField(default='', max_length=100)),
                ('are_you_rich_or_have_superpowers', models.IntegerField(choices=[(1, ' '), (2, 'Rich'), (3, 'Superpower'), (4, 'Both'), (5, 'Neither')], default=1)),
                ('if_so_what_superpower', models.IntegerField(choices=[(1, ' '), (2, 'Flight'), (3, 'Super Speed'), (4, 'Invisibility'), (5, 'Telekinesis'), (6, 'Healing'), (7, 'Super Strength'), (8, 'Elemental Powers'), (9, 'Energy Manipulation'), (10, 'Other')], default=1)),
                ('what_is_your_alignment', models.IntegerField(choices=[(1, ' '), (2, 'Good'), (3, 'Kinda Good'), (4, 'Neutral'), (5, 'Sorta Evil'), (6, 'Evil')], default=1)),
                ('give_3_cases_in_which_you_used_your_powers', models.TextField(default='', max_length=3000)),
            ],
        ),
    ]
